### ISSUE TITLE
[Feature request] Partial commits

### ISSUE THREAD

**Issue by KaKi87** [gitahead/gitahead#366] opened 2020-02-01 11:48 UTC
Hello,

I'd like to be able to make partial commits (i.e. committing specific lines of specific files) [just like in GitHub Desktop](https://github.blog/2015-01-14-partial-commits-in-github-for-windows/).

Thanks

**Comment by tommai78101** [comment] 2020-02-01 19:31
In other words, you want interactive staging using `git add -i` or `git add -p`.

**Comment by dcendents** [comment] 2020-02-04 16:39
This looks like a duplicate of #344

**Comment by hackhaslam** [comment] 2020-02-04 16:41
Agreed.

**Closed by hackhaslam** 2020-02-04 16:41 UTC

**Comment by KaKi87** [comment] 2020-02-04 17:47
Yes indeed, I didn't found out how to check. Thanks !
