### ISSUE TITLE
lua isn't found

### ISSUE THREAD

**Issue by yurivict** [gitahead/gitahead#249] opened 2019-08-09 20:54 UTC
I have these lua packages installed:
```
$ pkg info | grep ^lua
lua52-5.2.4                    Small, compilable scripting language providing easy access to C code
lua52-bitop-1.0.2_1            Bitwise operations on numbers
lua52-json-1.3.4               JSON parser/creator for Lua
lua52-lpeg-1.0.2               PEG-based pattern-matching library for Lua
lua52-luaexpat-1.3.0_4         LuaExpat is a SAX XML parser based on the Expat library
lua52-luasocket-3.0.r1_4,1     IPv4 and IPv6 socket support for the Lua language
lua53-5.3.5_3                  Powerful, efficient, lightweight, embeddable scripting language
```

Configure stage only prints this:
```
-- Checking for module 'libcmark'
--   Found libcmark, version 0.29.0
-- Checking for one of the modules 'lua-5.3;lua5.3;lua>=5.3'
-- Checking for module 'libsecret-1'
--   Found libsecret-1, version 0.18.6
```

It doesn't say if it found it or not.

Then there are failures:
```
[3/208] /usr/bin/cc   -O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing -O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing -MD -MT dep/lpeg/CMakeFiles/lpeg.dir/lpeg-1.0.1/lpcap.c.o -MF dep/lpeg/CMakeFiles/lpeg.dir/lpeg-1.0.1/lpcap.c.o.d -o dep/lpeg/CMakeFiles/lpeg.dir/lpeg-1.0.1/lpcap.c.o   -c /usr/ports/devel/gitahead/work/gitahead-2.5.8-15-gb601fd8/dep/lpeg/lpeg-1.0.1/lpcap.c
FAILED: dep/lpeg/CMakeFiles/lpeg.dir/lpeg-1.0.1/lpcap.c.o
/usr/bin/cc   -O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing -O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing -MD -MT dep/lpeg/CMakeFiles/lpeg.dir/lpeg-1.0.1/lpcap.c.o -MF dep/lpeg/CMakeFiles/lpeg.dir/lpeg-1.0.1/lpcap.c.o.d -o dep/lpeg/CMakeFiles/lpeg.dir/lpeg-1.0.1/lpcap.c.o   -c /usr/ports/devel/gitahead/work/gitahead-2.5.8-15-gb601fd8/dep/lpeg/lpeg-1.0.1/lpcap.c
/usr/ports/devel/gitahead/work/gitahead-2.5.8-15-gb601fd8/dep/lpeg/lpeg-1.0.1/lpcap.c:6:10: fatal error: 'lua.h' file not found
#include "lua.h"
         ^~~~~~~
```

FreeBSD 12 amd64

**Comment by hackhaslam** [comment] 2019-08-09 20:57
Is this before or after the change (#187) I just merged from @symphorien?

**Comment by yurivict** [comment] 2019-08-09 21:05
This is with 2.5.8-15-gb601fd8.

**Comment by symphorien** [comment] 2019-08-09 21:28
I can still build master (74104f52dd8ec36aa11c705bbcf4f7e400d103d6) without lua installed: 
```
-- Checking for module 'libcmark'
--   Found libcmark, version 0.28.3
-- Checking for one of the modules 'lua-5.3;lua5.3;lua>=5.3'
-- Checking for module 'libsecret-1'
--   Found libsecret-1, version 0.18.7
```

**Comment by yurivict** [comment] 2019-08-09 21:35
For me it looks for "lua.h".

**Comment by symphorien** [comment] 2019-08-09 21:42
It should be in `dep/lua/lua-5.3.4/src/lua.h`.

**Comment by symphorien** [comment] 2019-08-09 21:50
Also, what does `pkg-config --cflags lua-5.3` say ?

**Comment by yurivict** [comment] 2019-08-09 21:57
```
$ pkg-config --cflags lua-5.3
-I/usr/local/include/lua53 
```

Lua is installed in /usr/local.

**Comment by symphorien** [comment] 2019-08-09 22:00
Then I don't really understand why cmake does not find lua...

**Comment by hackhaslam** [comment] 2019-09-16 16:56
I backed out the change to search for lua with pkg-config. The problem isn't that it doesn't find lua, it's that it doesn't create an imported target with the correct include paths set.

**Closed by hackhaslam** 2019-09-16 16:56 UTC
