### ISSUE TITLE
Build instructions result in build failure on Linux

### ISSUE THREAD

**Issue by safield** [gitahead/gitahead#219] opened 2019-06-23 20:46 UTC
I am trying to build on Ubuntu derivative Linux Mint 19.1

I have followed the build instructions provided (except I switched from release to debug).

When running the following command in the instructions, build errors occur.
`
cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ../..`

The following is the output in the terminal. In addition, I have attached the error logs and outputs from cmake.
[CMakeError.log](https://github.com/gitahead/gitahead/files/3318552/CMakeError.log)
[CMakeOutput.log](https://github.com/gitahead/gitahead/files/3318553/CMakeOutput.log)

> 
> scott@scott-Z97-HD3:~/src/gitahead/build/debug$ cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ../..
> -- The following features have been enabled:
> 
>  * diffie-hellman-group-exchange-sha1, "new" diffie-hellman-group-exchange-sha1 method
> 
> -- The following OPTIONAL packages have been found:
> 
>  * Git
>  * OpenSSL
> 
> -- The following REQUIRED packages have been found:
> 
>  * Qt5Concurrent
>  * Qt5Core
>  * Qt5Gui
>  * Qt5Network
>  * Qt5PrintSupport
>  * Qt5Widgets
>  * Qt5Test
>  * Qt5 (required version >= 5.9)
> 
> -- The following features have been disabled:
> 
>  * Shared library, creating libssh2 as a shared library (.so/.dll)
>  * Compression, using zlib for compression
>  * "none" cipher
>  * "none" MAC
>  * Logging, Logging of execution with debug trace
> 
> -- Checking prototype qsort_r for HAVE_QSORT_R_BSD - False
> -- Checking prototype qsort_r for HAVE_QSORT_R_GNU - True
> -- Could NOT find HTTP_Parser (missing: HTTP_PARSER_INCLUDE_DIR HTTP_PARSER_LIBRARY) 
> -- http-parser version 2 was not found or disabled; using bundled 3rd-party sources.
> -- Enabled features:
>  * diffie-hellman-group-exchange-sha1, "new" diffie-hellman-group-exchange-sha1 method
>  * threadsafe, threadsafe support
>  * HTTPS, using OpenSSL
>  * SHA, using CollisionDetection
>  * http-parser, http-parser support (bundled)
>  * zlib, using system zlib
>  * SSH, SSH transport support
> 
> -- Disabled features:
>  * Shared library, creating libssh2 as a shared library (.so/.dll)
>  * Compression, using zlib for compression
>  * "none" cipher
>  * "none" MAC
>  * Logging, Logging of execution with debug trace
>  * debugpool, debug pool allocator
>  * tracing, tracing support
>  * SPNEGO, SPNEGO authentication support
>  * iconv, iconv encoding conversion support
> 
> -- Checking for module 'libsecret-1'
> --   No package 'libsecret-1' found
> CMake Error at pack/CMakeLists.txt:32 (get_target_property):
>   get_target_property() called with non-existent target "Qt5::QJpegPlugin".
> 
> 
> CMake Error at pack/CMakeLists.txt:33 (get_filename_component):
>   get_filename_component called with incorrect number of arguments
> 
> 
> CMake Error at pack/CMakeLists.txt:34 (get_filename_component):
>   get_filename_component called with incorrect number of arguments
> 
> 
> CMake Error at pack/CMakeLists.txt:35 (get_filename_component):
>   get_filename_component called with incorrect number of arguments
> 
> 
> CMake Error at pack/CMakeLists.txt:32 (get_target_property):
>   get_target_property() called with non-existent target
>   "Qt5::QXcbIntegrationPlugin".
> 
> 
> CMake Error at pack/CMakeLists.txt:33 (get_filename_component):
>   get_filename_component called with incorrect number of arguments
> 
> 
> CMake Error at pack/CMakeLists.txt:34 (get_filename_component):
>   get_filename_component called with incorrect number of arguments
> 
> 
> CMake Error at pack/CMakeLists.txt:35 (get_filename_component):
>   get_filename_component called with incorrect number of arguments
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/scott/src/gitahead/build/debug/CMakeFiles/CMakeOutput.log".
> See also "/home/scott/src/gitahead/build/debug/CMakeFiles/CMakeError.log".
>

**Comment by DeadMozay** [comment] 2019-07-11 11:15
This error on all linux distributions

**Comment by DeadMozay** [comment] 2019-08-14 04:23
The problem can be solved by removing a piece from pack / CMakeLists.txt responsible for the assembly is not for linux

**Comment by JoseTM** [comment] 2019-08-30 21:32
I built it with Qt/5.13.0. Indeed to build master branch I think instructions are wrong because they are using functions that are available only in qt >= 5.10

https://doc.qt.io/qt-5/qrandomgenerator.html

**Comment by jazzzz** [comment] 2019-09-18 14:42
> I built it (without modify CMakeLists.txt) with Qt/5.13.0. Indeed to build master branch I think instructions are wrong because they are using functions that are available only in qt >= 5.10

I have the same build failure with qt 5.12, so if it works with qt 5.13, it would mean that qt >= 5.13 is required.

**Comment by Mailaender** [comment] 2020-07-02 20:46
I tried to package this for @openSUSE and still got the same cmake error. Is it a missing dependency?

```
[   16s] CMake Error at pack/CMakeLists.txt:33 (get_target_property):
[   16s]   get_target_property() called with non-existent target "Qt5::QJpegPlugin".
[   16s] 
[   16s] 
[   16s] CMake Error at pack/CMakeLists.txt:34 (get_filename_component):
[   16s]   get_filename_component called with incorrect number of arguments
[   16s] 
[   16s] 
[   16s] CMake Error at pack/CMakeLists.txt:35 (get_filename_component):
[   16s]   get_filename_component called with incorrect number of arguments
[   16s] 
[   16s] 
[   16s] CMake Error at pack/CMakeLists.txt:36 (get_filename_component):
[   16s]   get_filename_component called with incorrect number of arguments
[   16s] 
[   16s] 
[   16s] CMake Error at pack/CMakeLists.txt:33 (get_target_property):
[   16s]   get_target_property() called with non-existent target
[   16s]   "Qt5::QXcbIntegrationPlugin".
[   16s] 
[   16s] 
[   16s] CMake Error at pack/CMakeLists.txt:34 (get_filename_component):
[   16s]   get_filename_component called with incorrect number of arguments
[   16s] 
[   16s] 
[   16s] CMake Error at pack/CMakeLists.txt:35 (get_filename_component):
[   16s]   get_filename_component called with incorrect number of arguments
[   16s] 
[   16s] 
[   16s] CMake Error at pack/CMakeLists.txt:36 (get_filename_component):
[   16s]   get_filename_component called with incorrect number of arguments
[   16s] 
[   16s] 
[   16s] CMake Error at pack/CMakeLists.txt:33 (get_target_property):
[   16s]   get_target_property() called with non-existent target
[   16s]   "Qt5::QComposePlatformInputContextPlugin".
[   16s] 
[   16s] 
[   16s] CMake Error at pack/CMakeLists.txt:34 (get_filename_component):
[   16s]   get_filename_component called with incorrect number of arguments
[   16s] 
[   16s] 
[   16s] CMake Error at pack/CMakeLists.txt:35 (get_filename_component):
[   16s]   get_filename_component called with incorrect number of arguments
[   16s] 
[   16s] 
[   16s] CMake Error at pack/CMakeLists.txt:36 (get_filename_component):
[   16s]   get_filename_component called with incorrect number of arguments
```

**Comment by Mailaender** [comment] 2020-07-02 20:48
Duplicate of https://github.com/gitahead/gitahead/issues/139 by the way.

**Comment by rubo77** [comment] 2020-09-09 05:52
> I have the same build failure with qt 5.12, so if it works with qt 5.13, it would mean that qt >= 5.13 is required.

It worked fine on Ubuntu 20.04 with `qt` version `5.12.8-0ubuntu1`

**Comment by hackhaslam** [comment] 2020-12-21 03:29
I believe this should be fixed now.

**Closed by hackhaslam** 2020-12-21 03:29 UTC
