### ISSUE TITLE
Symlinked ~/.gitconfig gets clobbered when using "edit config file" from within Gitahead

### ISSUE THREAD

**Issue by andgeno** [gitahead/gitahead#300] opened 2019-10-25 17:42 UTC
My symlink  `~/.gitconfig` got replaced with an more or less empty config file when I used the internal editor!

Reproduce:
- `ln -s ~/.dotfiles/.gitconfig ~/.gitconfig`   ## the file pointed to must exists. Looks like another bug where Gitahead does not check for existences and just crashes.
- Open Gitahead
- Go to menu: Tools | Options...
- Click "Edit config file..."
- You will see the editor with just one line "[global]" and on your disk you will see that the config got replaced with this content.

**Comment by andgeno** [comment] 2019-10-25 18:25
Looks like the missing support for a symlinked `.gitconfig` file results in a lot of trouble in this program. It does not allow to edit / select diff and merge tools. Any action inside Gitahead that needs/wants to modify the `.gitconfig` file will result in a clobbered config file.

**Comment by hackhaslam** [comment] 2019-10-25 18:26
Yes, this is a serious problem. I will try to investigate soon.

**Comment by hackhaslam** [comment] 2019-10-27 00:20
@andgeno I actually can't reproduce this. Can you describe your environment?

**Comment by andgeno** [comment] 2019-10-27 00:59
I'm running this on Windows 10. Symlinks have been enabled for non-admin users so symlinks actually work instead of just being silently copied by the OS.
The symlink is created using a Git Bash for Windows terminal. 

Let me know if you need more information.

**Comment by hackhaslam** [comment] 2019-10-30 20:49
This is fixed in version 2.5.11.

**Closed by hackhaslam** 2019-10-30 20:49 UTC
