### ISSUE TITLE
Stash operation slow and uses excessive disk i/o

### ISSUE THREAD

**Issue by safield** [gitahead/gitahead#158] opened 2019-02-14 19:28 UTC
Windows 10 1809
GitAhead 2.5.3

I attempted to perform a stash push operation using Git Ahead.

The operation took about 3-4 minutes to complete. The entire time gitahead was using about 25mb/s disk io. During this time the UI was unresponsive.

Afterwards I popped the stash, which was significantly faster, only about 500ms.

I then tried pushing the stash again. This time it took about 35 seconds to push the stash. It was faster, but really the operation should at most take about 5 seconds.

**Comment by hackhaslam** [comment] 2019-02-20 01:24
This looks like a regression in libgit2. It might be related to libgit2/libgit2#3910.

**Comment by safield** [comment] 2019-06-21 20:42
Looks like this could be resolved now in libgit2.

https://github.com/libgit2/libgit2/issues/3910#issuecomment-504246434

**Comment by hackhaslam** [comment] 2019-06-21 20:47
Yeah, I'll test that when it gets merged.

**Comment by hackhaslam** [comment] 2019-08-29 21:14
This has been fixed in libgit2 and is now in build 2.5.10 of GitAhead.

**Closed by hackhaslam** 2019-08-29 21:14 UTC
